// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPIw6.Context;

#nullable disable

namespace StudentAPIw6.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentAPIw6.Model.BoMon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("maBM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenBM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("BoMon");
                });

            modelBuilder.Entity("StudentAPIw6.Model.LopHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BoMonid")
                        .HasColumnType("int");

                    b.Property<string>("ChuyenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maBM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoMonid");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("StudentAPIw6.Model.SinhVien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DiemTB")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("lopHocId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("lopHocId");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("StudentAPIw6.Model.LopHoc", b =>
                {
                    b.HasOne("StudentAPIw6.Model.BoMon", "BoMon")
                        .WithMany("lopHocs")
                        .HasForeignKey("BoMonid");

                    b.Navigation("BoMon");
                });

            modelBuilder.Entity("StudentAPIw6.Model.SinhVien", b =>
                {
                    b.HasOne("StudentAPIw6.Model.LopHoc", "lopHoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("lopHocId");

                    b.Navigation("lopHoc");
                });

            modelBuilder.Entity("StudentAPIw6.Model.BoMon", b =>
                {
                    b.Navigation("lopHocs");
                });

            modelBuilder.Entity("StudentAPIw6.Model.LopHoc", b =>
                {
                    b.Navigation("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
